# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
	follow_mouse = 0 # 0|1|2|3
	float_switch_override_focus = 2
	accel_profile = flat
	tablet {
		transform = 0
		left_handed = 0

	}
	kb_layout = us
}
